// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4wHKQyLr04YMSqyGa4KZ3RFFWkZ_Q61g',
    appId: '1:304533883144:web:70a2a299c7ab41cac544bd',
    messagingSenderId: '304533883144',
    projectId: 'zaliczenie-1ce25',
    authDomain: 'zaliczenie-1ce25.firebaseapp.com',
    storageBucket: 'zaliczenie-1ce25.appspot.com',
    measurementId: 'G-WZKX9DT6RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlqQ2Ow39azJ7S4aB_qMsfZYVBdSTYT30',
    appId: '1:304533883144:android:1780b4c5ffbc64a5c544bd',
    messagingSenderId: '304533883144',
    projectId: 'zaliczenie-1ce25',
    storageBucket: 'zaliczenie-1ce25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ5c4cIxL2Sp5Jag-qsMzfAtP_tUIYaYo',
    appId: '1:304533883144:ios:734d476fcd2e24b9c544bd',
    messagingSenderId: '304533883144',
    projectId: 'zaliczenie-1ce25',
    storageBucket: 'zaliczenie-1ce25.appspot.com',
    iosClientId:
        '304533883144-072m55i0uinkduujmrnvo66bho5tnurq.apps.googleusercontent.com',
    iosBundleId: 'com.example.zaliczenie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ5c4cIxL2Sp5Jag-qsMzfAtP_tUIYaYo',
    appId: '1:304533883144:ios:734d476fcd2e24b9c544bd',
    messagingSenderId: '304533883144',
    projectId: 'zaliczenie-1ce25',
    storageBucket: 'zaliczenie-1ce25.appspot.com',
    iosClientId:
        '304533883144-072m55i0uinkduujmrnvo66bho5tnurq.apps.googleusercontent.com',
    iosBundleId: 'com.example.zaliczenie',
  );
}
